#!/usr/bin/env bash

g++ -std=c++17 -g -lpqxx -lpq -lpthread -pthread -luuid -I include -L /usr/include/pqxx src/main.cpp include/database/DatabaseConnection.cpp include/server/libsocket_listener.a -o kserver
