#!/usr/bin/env bash

g++ -std=c++17 -g -lpqxx -lpq -lpthread -pthread -luuid -I include -L /usr/include/pqxx src/main.cpp include/database/DatabaseConnection.cpp src/socket_listener.cpp src/task_queue.cpp /usr/local/lib/libpqxx.a -o kserver
