#!/usr/bin/env bash

g++ -std=c++17 -Wall -g -lpq -lpthread -pthread -luuid -I include -I /usr/local/include/pqxx -L /usr/local/include/pqxx src/main.cpp include/database/DatabaseConnection.cpp include/server/libsocket_listener.a -o kserver
