version: 2.1
jobs:
  compile:
    docker:
      - image: logicp/kserver:1.0.0
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: compile
          command: |
            ln -s /usr/include/pqxx /usr/local/include/pqxx && cmake . && make
      - store_artifacts:
          path: kserver
          destination: kserver
      - run:
          name: test
          command: |
            test/./kserver_test
      - run:
          name: notify_production
          command: |
            curl http://artifact.stronglogicsolutions.com/?artifact=kserver

workflows:
 version: 2
 build:
   jobs:
     - compile
