version: 2.1
jobs:
  compile:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - run:
          name: compile
          command: |
            echo 'Hello World!'

workflows:
 version: 2
 build:
   jobs:
     - compile

