version: 2.1
jobs:
  compile:
    docker:
      - image: logicp/kserver:1.0.0
    steps:
      - checkout
      - run:
          name: distro
          command: |
            pacman -S --noconfirm libsodium zeromq
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: ls -la include/config
      - run:
          name: compile
          command: |
            BUILD_ENV=CIRCLECI cmake . && make
      - store_artifacts:
          path: kserver
          destination: kserver
      - run:
          name: test
          command: |
            cd test && ./kserver_test
      - run:
          name: notify_production
          command: |
            curl http://artifact.stronglogicsolutions.com/?artifact=kserver

workflows:
 version: 2
 build:
   jobs:
     - compile
