version: 2.1
jobs:
  compile:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - checkout
      - run:
          name: db deps
          command: |
            git clone https://github.com/jtv/libpqxx && cd libpqxx && cmake . && make && make install
      - run:
          name: compile
          command: |
            ./compile

workflows:
 version: 2
 build:
   jobs:
     - compile

