version: 2.1
jobs:
  compile:
    docker:
      - image: logicp/kserver:1.0.0
    steps:
      - checkout
      - run:
          name: compile
          command: |
            ln -s /usr/include/pqxx /usr/local/include/pqxx && \
            cmake . && make
      - store_artifacts:
          path: kserver
          destination: kserver
      - run:
        name: test
        working_directory: $CIRCLE_WORKING_DIRECTORY/test
        command: |
          ./kserver_test
      - run:
          name: notify_production
          command: |
            curl http://artifact.stronglogicsolutions.com/?artifact=kserver

workflows:
 version: 2
 build:
   jobs:
     - compile

