version: 2.1
jobs:
  compile:
    docker:
      - image: buildpack-deps:18.04
        environment:
          - TZ: "America/Toronto"
          - DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run:
          name: db deps
          command: |
            apt-get update && apt-get install -y -qq cmake libpq-dev postgresql postgresql-contrib && /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start && git clone https://github.com/jtv/libpqxx && cd libpqxx && cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/ . && make && make install
      - run:
          name: compile
          command: |
            ./compile

workflows:
 version: 2
 build:
   jobs:
     - compile

