version: 2.1
jobs:
  compile:
    docker:
      - image: logicp/kserver:1.2.0
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --recursive --init
      - run: git submodule update --recursive --remote
      - run:
          name: build deps
          command: |
            cd /kserver/third_party/klogger && mkdir build && cd build && cmake .. && make -j && cd /kserver/include/codec && /
            flatc --cpp generictask.fbs && flatc --cpp instatask.fbs && flatc --cpp kmessage.fbs
      - run:
          name: compile
          command: |
            BUILD_ENV=CIRCLECI cmake . && make
      - store_artifacts:
          path: kserver
          destination: kserver
      - run:
          name: test
          command: |
            cd test && ./kserver_test
      - run:
          name: notify_production
          command: |
            curl http://artifact.stronglogicsolutions.com/?artifact=kserver

workflows:
 version: 2
 build:
   jobs:
     - compile
