version: 2.1
jobs:
  compile:
    docker:
      - image: logicp/kserver:0.0.1
    steps:
      - checkout
      - run:
          name: compile
          command: |
            ./compile

workflows:
 version: 2
 build:
   jobs:
     - compile

