#include "mock_data.hpp"
#include <string>

std::string loremIpsum{
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur convallis sem a consectetur. Maecenas ornare sem eget bibendum consequat. In hac habitasse platea dictumst. Etiam vulputate ex at malesuada tempus. Vestibulum vitae ultricies justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis cursus sodales cursus."
"Phasellus maximus orci quis quam aliquam maximus. In sit amet purus erat. Duis vitae justo vitae purus finibus elementum. Nulla consectetur diam vitae mauris fermentum pretium. Vivamus auctor lacus finibus, semper lorem sit amet, imperdiet odio. Etiam finibus mauris id felis fermentum porta at sit amet lectus. In posuere imperdiet ligula non ornare."
"Aliquam id elementum libero. Suspendisse quis erat sit amet quam scelerisque vehicula sit amet quis lacus. Sed consequat, mauris at varius elementum, erat est egestas ante, imperdiet bibendum lorem est at lectus. Proin euismod eget enim quis eleifend. Sed sit amet sagittis orci. Donec ornare lorem at facilisis condimentum. Vestibulum eros sem, egestas non orci quis, pretium vehicula augue. Donec ultrices erat scelerisque, iaculis neque at, aliquam mi. Donec ultricies interdum maximus."
"Donec et fermentum eros. Phasellus aliquet, lectus nec fermentum pharetra, purus lectus gravida erat, et dignissim erat risus vel lorem. Sed posuere ligula leo, at scelerisque nunc dapibus eget. Fusce molestie turpis ut iaculis ultricies. Nunc at aliquam orci. Sed dapibus egestas sollicitudin. Maecenas sed erat ut lectus maximus faucibus et ut sapien. Nam cursus urna dui, eget egestas nibh interdum at."
"Sed ultrices, dolor sit amet facilisis suscipit, est tellus hendrerit dui, quis volutpat purus nunc ut sem. Proin in accumsan dolor. Nunc pulvinar congue nunc eget euismod. Ut maximus maximus urna. In luctus nulla eu est ornare, ut rhoncus augue cursus. Curabitur sit amet dui vitae mauris finibus feugiat nec eu augue. Nullam ut sapien eget nisi posuere viverra ac id ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas."
"Sed aliquam laoreet ante, id pellentesque ante finibus et. Proin lorem nibh, aliquam scelerisque pulvinar sed, fringilla vel quam. Aenean eu rutrum tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tempus sem at sapien vehicula facilisis. Nam ultrices, magna quis molestie volutpat, orci ante pellentesque odio, non maximus nisl lacus quis ipsum. Cras efficitur id orci eget elementum. Fusce tristique consequat cursus. Donec sed sem in metus vestibulum feugiat a a tellus."
"Duis bibendum erat eget sem imperdiet, sed sagittis purus interdum. Nam mi massa, pretium id libero eget, posuere tempus dui. Pellentesque maximus vel ex ullamcorper ultrices. Sed dictum lorem vel efficitur rutrum. Ut at massa rhoncus, fringilla odio ut, porta lacus. Mauris vitae vestibulum velit. Quisque faucibus tincidunt felis quis pellentesque. Duis malesuada arcu massa, at auctor tortor convallis a. Nullam hendrerit metus non tellus interdum tincidunt. Morbi maximus luctus nulla. Donec eget lacus vel tellus bibendum tincidunt vitae quis leo."
"Cras aliquet odio lectus, et suscipit leo sodales at. Ut interdum justo vitae euismod cursus. Sed ut bibendum ante, sed molestie purus. Cras blandit lacus quam, eget interdum orci semper et. Maecenas quis tortor venenatis, aliquet nunc et, iaculis tortor. Vivamus varius facilisis augue nec aliquam. Vivamus elit leo, vestibulum ut urna eget, hendrerit bibendum ante. Aliquam venenatis, mi tincidunt blandit ornare, est purus hendrerit diam, at tincidunt felis arcu ac enim. Sed tristique elementum tincidunt. Quisque iaculis a augue vel malesuada. Aliquam in dolor nec est luctus scelerisque at a tellus. Maecenas placerat magna mauris, vitae semper augue vehicula at."
"Aenean sagittis tincidunt ligula, et vehicula lacus. Donec blandit cursus fringilla. Fusce a metus quis dolor convallis pretium eu ac nunc. Nam ut mattis justo, eget placerat eros. Morbi vitae neque ac ex consectetur eleifend. Nam euismod molestie sapien in volutpat. Quisque fringilla enim et diam lacinia posuere. Donec ac ante a urna vestibulum consequat. Ut eget vehicula nisi. Ut tortor purus, vehicula eu tempor sit amet, sodales at lorem. Vivamus massa nibh, ullamcorper ac pharetra eu, rhoncus vitae arcu. Phasellus at ultrices eros, eget pretium diam. Sed vehicula sed nisl sed mattis. Sed maximus augue vitae tellus tristique, maximus blandit ipsum ultrices. Nam convallis, nisl in fringilla rhoncus, enim ex convallis tortor, id posuere justo diam id nisl. Fusce laoreet leo et pharetra sagittis."
};
